GET https://example.com/comments
    ?page=2
    &pageSize=10


###

GET http://localhost:3000/?prompt=samsung

###

POST https://672c092a9d81ee5802fd.appwrite.global/ HTTP/1.1
Content-Type: application/json

{
  "integrations": "Santander Chile, BBVA Chile, BancoEstado, Itaú Corpbanca, Scotiabank Chile, Bci, Banco de Chile, Banco Security, Banco Internacional, Banco Falabella, CrediChile, Getnet"
}

###

GET http://localhost:3000/?prompt=gestion_de_inventario


###

GET https://674a4efa5ad1cf2d342a.appwrite.global/?prompt=videollamadas HTTP/1.1