GET https://example.com/comments
    ?page=2
    &pageSize=10


###

GET http://localhost:3000/?prompt=samsung

###

POST http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
  "integrations": "i need 2 integrations Onepay and BancoEstado"
}
